### ISSUE TITLE
Change card account clears secondary linked account

### ISSUE THREAD

**Issue by nimpie** [woudt/bunq2ifttt#1]
When I change the account linked to a card, the secondary account is cleared and needs to be setup manually in the bunq app again. The secondary account needs to be passed too in the call to the bunq api.

**Comment by woudt** [comment]
I believe this is a limitation of the bunq API. At least the [documentation](https://doc.bunq.com/) under 'What can my apps do with OAuth?', specifically refers to the ability to 'Change the **primary** monetary to which a Card is linked to', specifically mentioning primary only (and not secondary).

Now I didn't experiment if - despite the documentation - it works anyway. Did you try it?

**Comment by nimpie** [comment]
I have changed the code in a dirty way to retrieve my card details, pickup the secondary monetary account id and pass it to the pin assignment array. That works.

**Comment by woudt** [comment]
Thanks for testing this. I will work on a fix for this!

**Comment by woudt** [comment]
It took me a while, but this issue is now fixed in release 2.1. As an added bonus, changing the secondary account is now also supported.
