### ISSUE TITLE
Add account name to IFTTT Ingredients

### ISSUE THREAD

**Issue by jdambacher** [woudt/bunq2ifttt#4]
It would be nice if the account name (name of the account in bunq) could be added as a ingredient. Currently it's only possible to get the account IBAN (IBAN of the account in bunq).

I'm also using the ifttt2ynab service and it's not really comfortable to have the account IBAN as account name in YNAB.

**Comment by woudt** [comment]
Thanks for the request. This shouldn't be a big problem. I'll have a look and will let you know as soon as it is done!

**Comment by jdambacher** [comment]
@woudt Thanks for the fast response!

**Comment by woudt** [comment]
@jdambacher No problem.

This has just been fixed in release v2.3. I still need to update the documentation, but the slug 'account_name' will give you the account name.

**Comment by jdambacher** [comment]
Thanks, I'll try it!

**Comment by woudt** [comment]
Documentation is now here:
https://github.com/woudt/bunq2ifttt/wiki/Configure-payment-request-action

I am closing this issue now, though let me know if you encounter any problems or if you have any other suggestions for new features.

**Comment by jdambacher** [comment]
@woudt I've tried 'account_name' but it's still using the IBAN.
I've added 'account_name' to the ingredients and changed the applet to use the account_name instead of the IBAN to get the right account in YNAB.

**Comment by woudt** [comment]
@jdambacher Hmm, that is weird, as it is working for me.

- Is the name shown in the web interface?
- Did you configure the ingredient like the following screenshot?: https://raw.githubusercontent.com/woudt/bunq2ifttt/master/media/ifttt_mutation_ingredient_accountname.png
- If you make a simple applet, sending a notification or email, with just the text {{Account}}{{AccountName}} does it then send the IBAN twice?

**Comment by jdambacher** [comment]
@woudt 

1. Yes
2. Yes
3. No, the field is completely empty.

**Comment by woudt** [comment]
@jdambacher Hmm, very weird.

Are you sure your upgrade of bunq2IFTTT to release 2.3 was successful?
The API tests in IFTTT, do they all succeed?

If the answer is yes to both questions above, the only next step I see is to add some debugging code, so let me know.

**Comment by woudt** [comment]
@jdambacher Futhermore, in the log file there should be a line that starts with '[bunqcb_mutation] translated:'. In the json string after that, is the account_name field present and filled?

**Comment by jdambacher** [comment]
I've re-deployed the latest version and will try it again. I can find the mutation in the logs, but the account_name field is not present.

**Comment by jdambacher** [comment]
Ahhh ... maybe I found the issue. I was deploying both YNAB and BUNQ integration to the same Google Cloud App. I modified the app.yaml to set the service name for each application. After updating your code (for the BUNQ integration), I forgot the re-add the service declaration to the app.yaml. I'll try it now and will inform you on my next transaction.

**Comment by jdambacher** [comment]
It's working now! I think the issue was the service name.

Thanks for your support!
